---
title: "Laptop Pricing"
author: "Attila Szuts"
date: "02/01/2021"
output: html_document
editor_options: 
  chunk_output_type: console
abstract: "This analysis will try to answer how you can price a laptop based on its specifications and how you can try to find good deals among them. It uses 1300 data points to build a linear regression model on price."
---



```{r include=FALSE}
rm(list = ls())
library(tidyverse); library(janitor); library(estimatr); library(MASS); library(moments); library(car)
laptops <- "data/raw/laptop-price/"
raw1 <- read_csv(paste0(laptops, "laptop_price.csv")) %>% clean_names()
```

```{r include=FALSE}
pattern <- "([:digit:]{3,4}x[:digit:]{3,4})" # pattern to match screen resolutions
  
# data cleaning
laptop <- raw1 %>% 
  mutate(ram = as.numeric(gsub("GB", "", raw1$ram)), # convert RAM to numeric, in GB
         weight = as.numeric(gsub("kg", "", raw1$weight))) %>% # convert weight to numeric, in kg
  # create group dummies for screen size
  mutate(screen_small = ifelse(inches < 15, T, F), 
         screen_mid = ifelse(inches >= 15 & inches < 17, T, F),
         screen_big = ifelse(inches >= 17, T, F)) %>% 
  # extract resolution
  mutate(touchscreen = ifelse(grepl("Touchscreen", raw1$screen_resolution), T, F), # touchscreen dummy
         ips = ifelse(grepl("IPS", raw1$screen_resolution), T, F), # IPS display dummy
         resolution = str_extract_all(raw1$screen_resolution, pattern, simplify = T)) %>% 
  dplyr::select(-screen_resolution) %>% 
  mutate(cpu = tolower(trimws(cpu))) %>% # trim whitespace
  add_column(lencpu = sapply(strsplit(raw1$cpu, " "), length)) %>% 
  mutate(op_sys = tolower(ifelse(grepl("macosx", tolower(gsub(" ", "", op_sys))), "macos" , gsub(" ", "", op_sys))))

  
# number of words in cpu column
temp <- laptop %>% 
  group_by(cpu) %>% 
  summarise(count = n())
temp <- temp %>% 
  add_column(lencpu = sapply(strsplit(temp$cpu, " "), length)) %>% 
  arrange(lencpu, cpu)

# function that extract cpu manufacturer, cpu model, cpu model variant, cpu frequency and number of cores
cpuMan <- function(x) {
  outlist <- c()
  for (e in 1:length(x$cpu)) {
    outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[1]])
  }
  return(outlist)
}
cpuModel <- function(x) {
  outlist <- c()
  for (e in 1:length(x$cpu)) {
    if (x$lencpu[e] == 5 & grepl("xeon", x$cpu[e]) != T)  {
      outlist <- c(outlist, paste(strsplit(x$cpu[e], split = " ")[[1]][[2]], strsplit(x$cpu[e], split = " ")[[1]][[3]]))
    } else if (x$lencpu[e] == 4 & x$cpu_manufac[e] == "intel") {
      outlist <- c(outlist, paste(strsplit(x$cpu[e], split = " ")[[1]][[2]], strsplit(x$cpu[e], split = " ")[[1]][[3]]))
    } else {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[2]])
    }
  }
  return(outlist)
}
cpuVariant <- function(x) {
  outlist <- c()
  for (e  in 1:length(x$cpu)) {
    if (x$lencpu[e] == 4 & x$cpu_manufac[e] != "amd") {
      outlist <- c(outlist, NA)
    } else if (x$lencpu[e] == 4) {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[3]])
    } else if (x$lencpu[e] == 5 & grepl("xeon", x$cpu[e]) != T) {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[4]])
    } else if (x$lencpu[e] == 5 & grepl("xeon", x$cpu[e]) == T) {
      outlist <- c(outlist, paste(strsplit(x$cpu[e], split = " ")[[1]][[3]], strsplit(x$cpu[e], split = " ")[[1]][[4]]))
    } else {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[5]])
    }
  }
  return(outlist)
}
cpuFreq <- function(x) {
  outlist <- c()
  for (e in 1:length(x$cpu)) {
    if (x$lencpu[e] == 4) {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[4]])
    } else if (x$lencpu[e] == 5) {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[5]])
    } else {
      outlist <- c(outlist, strsplit(x$cpu[e], split = " ")[[1]][[6]])
    }
  }
  return(outlist)
}
cpuCores <- function(x) {
  outlist <- c()
  for (e in 1:length(x$cpu)) {
    if (x$lencpu[e] == 6) {
      outlist <- c(outlist, paste(strsplit(x$cpu[e], split = " ")[[1]][[3]], strsplit(x$cpu[e], split = " ")[[1]][[4]]))
    } else {
      outlist <- c(outlist, NA)
    }
  }
  return(outlist)
}
# create function that extracts storage size and type
memory <- function(x) {
  outlist <- list()
  ssd <- c()
  hdd <- c()
  for (e in 1:length(x$memory)) {
    if (x$ssd[e] == T & x$hdd[e] == F) {
      ssd <- c(ssd, str_extract(x$memory[e], "[:digit:]+tb|[:digit:]+gb")[[1]])
      hdd <- c(hdd, 0)
    } else if (x$ssd[e] == F & x$hdd[e] == T) {
      hdd <- c(hdd, str_extract(x$memory[e], "[:digit:]+tb|[:digit:]+gb|1\\.0tb")[[1]])
      ssd <- c(ssd, 0)
    } else {
      tryCatch(
        expr = {
          if (grepl("hybrid", x$memory[e])) {
            hdd <- c(hdd, str_extract_all(x$memory[e], "[:digit:]+gb|[:digit:]+\\.*[:digit:]*tb")[[1]][[1]])
            ssd <- c(ssd, 0)
          } else {
            ssd <- c(ssd, str_extract_all(x$memory[e], "[:digit:]+gb|[:digit:]+\\.*[:digit:]*tb")[[1]][[1]])
            hdd <- c(hdd, str_extract_all(x$memory[e], "[:digit:]+gb|[:digit:]+\\.*[:digit:]*tb")[[1]][[2]])
          }},
        error = function(er) {
          message("there was an error")
          print(laptop$memory[e])
          if (x$ssd[e] == T & x$hdd[e] == F) {
            print("ssd")
          } else if (x$ssd[e] == F & x$hdd[e] == T) {
            print("hdd")
          } else {
            print(paste(str_extract_all(x$memory[e], "[:digit:]+gb|[:digit:]+\\.*[:digit:]*tb")[[1]][[1]], str_extract_all(x$memory[e], "[:digit:]+gb|[:digit:]+\\.*[:digit:]*tb")[[1]][[2]]))
          }
          }
        )
    }
  }
  outlist <- list(ssd = ssd, hdd = hdd)
  return(outlist)
}

# create function that extracts gpu manufacturers
gpuMan <- function(x) {
  outlist <- c()
  for (e in 1:length(x$gpu)) {
    outlist <- c(outlist, strsplit(x$gpu[e], split = " ")[[1]][[1]])
  }
  return(outlist)
}

# add new columns with cleaned cpu data
laptop <- laptop %>% 
  add_column(cpu_manufac = cpuMan(laptop)) # extract manufacturer
laptop <- laptop %>% 
  add_column(cpu_model = cpuModel(laptop), # extract cpu model 
             cpu_model_variant = cpuVariant(laptop), # extract cpu model variant
             cpu_freq = cpuFreq(laptop), # extract cpu clock frequency
             cpu_cores = cpuCores(laptop) # extract cpu cores
             ) %>% 
  mutate(cpu_freq = as.numeric(gsub("ghz", "", cpu_freq, ignore.case = T))) %>% 
  dplyr::select(-c(lencpu, cpu_cores, cpu)) %>% 
  # clean memory
  mutate(memory = tolower(trimws(memory)), 
         ssd = ifelse(grepl("ssd|flash|hybrid", memory), T, F), # create ssd dummy
         hdd = ifelse(grepl("hdd|hybrid", memory), T, F), # create hdd dummy
         memory_type = ifelse(ssd == T & hdd == F, "ssd", ifelse(ssd == F & hdd == T, "hdd", ifelse(ssd == T & hdd == T, "both", "none"))))

laptop <- laptop %>% 
  add_column(ssd_size = memory(laptop)["ssd"][[1]], hdd_size = memory(laptop)["hdd"][[1]]) %>%  # add column for ssd and hdd size
  mutate(hdd_size = ifelse(grepl("tb", hdd_size), as.numeric(gsub("tb", "", hdd_size))*1000, as.numeric(gsub("gb", "", hdd_size))), # transform to GB
         ssd_size = ifelse(grepl("gb", ssd_size), as.numeric(gsub("gb", "", ssd_size)), as.numeric(gsub("tb", "", ssd_size))*1000), # transform to GB
         gpu = tolower(trimws(gpu)), 
         gpu_type = ifelse(grepl("intel hd|intel uhd|intel graphics|intel iris", gpu), "integrated", gpu)) %>%   # does the laptop have a graphics card or is it integrated
  dplyr::select(-c(gpu, memory))

# change reference level
laptop <- laptop %>% 
  mutate(company = relevel(as.factor(company), ref = "Lenovo")) %>% 
  pivot_longer(cols = c("screen_small", "screen_mid", "screen_big"), names_to = "screen_category") %>% 
  filter(value == T) %>% 
  mutate(type_name = relevel(as.factor(type_name), ref = "Notebook"),
         op_sys = relevel(as.factor(op_sys), ref = "windows10"),
         screen_category = relevel(as.factor(screen_category), ref = "screen_mid"),
         resolution = relevel(as.factor(resolution), ref = "1920x1080"),
         cpu_model = relevel(as.factor(cpu_model), ref = "core i7"),
         memory_type = relevel(as.factor(memory_type), ref = "ssd"),
         gpu_type = relevel(as.factor(gpu_type), ref = "integrated"),
         ln_price = log(price_euros))
```


```{r include=FALSE}
# create training-test sample
## 80% of the sample size
smp_size <- floor(0.8 * nrow(laptop))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(laptop)), size = smp_size)

laptop_all <- laptop
laptop_test <- laptop[-train_ind, ]
laptop <- laptop[train_ind, ]

# clean directory
rm(temp, pattern, cpuMan, cpuModel, cpuVariant, cpuFreq, cpuCores, raw1)
```

```{r include=FALSE}
summary(laptop$price_euros)

skewness(laptop$price_euros)
skewness(sqrt(laptop$price_euros))
skewness(log(laptop$price_euros))

ggplot(aes(price_euros), data = laptop) + geom_histogram(bins = 50, color = "black", fill = "grey") + theme_bw()
ggplot(aes(sqrt(price_euros)), data = laptop) + geom_histogram(bins = 50, color = "black", fill = "grey") + theme_bw()
ggplot(aes(log(price_euros)), data = laptop) + geom_histogram(bins = 50, color = "black", fill = "grey") + theme_bw()
```

```{r include=FALSE}
scatterfun <- function(x) {
  ggplot(aes(x, ln_price), data = laptop) +
    geom_point(position = "jitter", alpha = 0.4) + 
    geom_smooth(method = "loess") +
    theme_bw()
}
boxfun <- function(x) {
  ggplot(aes(x, ln_price), data = laptop) + 
    geom_boxplot() + 
    theme_bw() + 
    stat_summary(fun.data = give.n, geom = "text")
}
# function to display sample size in boxplots
give.n <- function(x){
   return(c(y = mean(x), label = length(x)))
}
# residuals function
resids <- function(x, y) {
  # x : data to use
  # y : model to use
  # x$reg3_pred_vals <- y$fitted.values
  x$reg3_pred_vals <- predict(y, x)
  x$reg3_res <- x$ln_price - x$reg3_pred_vals
  x$reg3_pred_exp <- exp(x$reg3_pred_vals)
  x$reg3_res_exp <- x$price_euros - x$reg3_pred_exp
  return(x)
}
```

```{r include=FALSE}
boxfun(laptop$company)
boxfun(laptop$type_name)
scatterfun(laptop$inches)
boxfun(laptop$screen_category)
boxfun(laptop$touchscreen)
boxfun(laptop$ips)
boxfun(laptop$resolution)
scatterfun(laptop$ram)
scatterfun(laptop$gpu_type)
boxfun(laptop$cpu_manufac)
boxfun(laptop$cpu_model)
scatterfun(laptop$cpu_freq)
boxfun(laptop$memory_type)
scatterfun(laptop$ssd_size)
scatterfun(laptop$hdd_size)
boxfun(laptop$op_sys)
scatterfun(laptop$weight)
```

Baseline model: $\text{reg1} : \text{ln_price} = \alpha + \beta * \text{company}$.

```{r include=FALSE}
reg1 <- lm_robust(ln_price ~ company, data = laptop)
summary(reg1)
```

```{r include=FALSE}
reg2 <- lm(ln_price ~ company + type_name + inches + ram + op_sys + weight + 
            screen_category + touchscreen + ips + resolution + cpu_manufac + 
            cpu_model + memory_type + ssd_size + hdd_size + gpu_type, 
          data = laptop)

scope_list = list(upper = ~company + type_name + inches + ram + op_sys + weight + 
                    screen_category + touchscreen + ips + resolution + cpu_manufac + 
                    cpu_model + memory_type + ssd_size + hdd_size + gpu_type, lower = ~1)

step <- stepAIC(reg2, direction="both", scope = scope_list)
step$anova

step_formula <- as.character(formula(step))
step_formula <- paste(step_formula[2], step_formula[1], step_formula[3])
```

Extended model: `r step_formula`

# Model Assumptions
```{r include=FALSE}
reg3 <- lm(step_formula, data = laptop)

laptop <- resids(laptop, reg3)
```


## Outliers and influential cases
```{r include=FALSE}
laptop$reg3_res <- resid(reg3)
laptop$rstand <- rstandard(reg3)
laptop$rstudent <- rstudent(reg3)
laptop$cookd <- cooks.distance(reg3)
laptop$dfbeta <- dfbeta(reg3)
laptop$dffit <- dffits(reg3)
laptop$leverage <- hatvalues(reg3)
laptop$covratio <- covratio(reg3)

# large residuals
large_resid <- laptop[laptop$rstand > 2 | laptop$rstand < - 2,]
large_resid <- large_resid[!is.na(large_resid$rstand),] %>% 
  dplyr::select(laptop_id, company, product, price_euros, reg3_pred_exp, ln_price, reg3_pred_vals, rstand, cookd, leverage, covratio) %>% 
  arrange(desc(abs(rstand)))

# are large residuals also influential?
k <- length(strsplit(x = gsub("~", "+", step_formula), split = " + ", fixed = T)[[1]]) - 1 # number of predictors variables in model
n <- nrow(laptop) # number of observations


# cooks distance
large_resid[large_resid$cookd > 1,] # empty

# covariance ratio
cvr_upr <- 1 + (3*(k + 1) / n)
cvr_lwr <- 1 - (3*(k + 1) / n)
large_resid %>% 
  mutate(cvr_crit = ifelse(cvr_lwr > covratio | cvr_upr < covratio, T, F)) %>% 
  filter(cvr_crit) %>% 
  dplyr::select(-cvr_crit) %>% 
  arrange(desc(abs(covratio))) %>% view()

# leverage
avg_leverage <- k + 1/n
large_resid[large_resid$leverage > avg_leverage * 2,] # empty
```

## Multicollinearity

```{r include=FALSE}
mean(vif(reg3))
alias(reg3)

```

## Residuals - homoskedasticity and normality

```{r include=FALSE}
laptop %>% 
  ggplot(aes(rstudent)) + 
  geom_histogram(fill = "grey", color = "black") + 
  theme_bw() + 
  labs(x = "Studentized residual",
       y = "")

laptop %>% 
  ggplot(aes(reg3_pred_vals, rstudent)) + 
  geom_point() + 
  theme_bw() + 
  geom_smooth(method = "lm", color = "blue") +
  labs(x = "Fitted values",
       y = "Studentized Residuals")
```

## Independent errors

```{r include=FALSE}
car::dwt(reg3) # no autocorrelation almost perfect
```

Residuals

```{r include=FALSE}
summary(reg3)

#overpriced
laptop %>% 
  top_n(5, reg3_res) %>% 
  arrange(desc(reg3_res)) %>% 
  dplyr::select(company, product, price_euros, reg3_pred_exp)
# underpriced
laptop %>% 
  top_n(-5, reg3_res) %>% 
  arrange(reg3_res) %>% 
  dplyr::select(company, product, price_euros, reg3_pred_exp)
```

$\text{Y}-\hat{\text{Y}}$ plot

```{r include=FALSE}
laptop %>% 
  ggplot(aes(reg3_pred_vals, ln_price)) + 
  geom_point() + 
  theme_bw() + 
  labs(x = "Predicted log-price",
       y = "Actual log-price",
       title = "Y - Y hat plot")
laptop %>% 
  ggplot(aes(reg3_pred_exp, price_euros)) + 
  geom_point() + 
  theme_bw() + 
  labs(x = "Predicted price",
       y = "Actual price",
       title = "Y - Y hat plot")
```

Prediction intervals

```{r include=FALSE}
laptop %>% 
  add_column(pred_lwr = predict(reg3, newdata = laptop, interval = "prediction", alpha = 0.05)[,2],
             pred_upr = predict(reg3, newdata = laptop, interval = "prediction", alpha = 0.05)[,3],
             ci_lwr = predict(reg3, newdata = laptop, interval = "confidence", alpha = 0.05)[,2],
             ci_upr = predict(reg3, newdata = laptop, interval = "confidence", alpha = 0.05)[,3])
```

```{r}

```

